import type { WorkflowStep } from '../types';
export const LEGACY_ENZYME_STEPS: WorkflowStep[] = [
  {
    id: "step-1",
    order: 1,
    title: "课题立项与目标定义",
    category: "研发启动 · 论证",
    description: "确立耐高温植酸酶重塑指标，明确 Tm ≥ 85℃ 且比活力不低于野生型 80% 的总体目标",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-03-10 14:00",
    leadPerson: "张立华 PI",
    schemeTitle: "立项任务书与技术可行性论证方案",
    schemeCount: 3,
    refCount: 12,
    schemeNote: "已通过专家委员会立项初审与生物安全备案",
    reportSummary: "完成国内外同类酶学热稳定性及专利壁垒全面检索报告",
    reportCount: 3,
    indicatorCount: 4,
    attachmentName: "《Phytase_Project_Kickoff_Report.pdf》",
    datasetSummary: "2 个公共数据集 · 4 个文献附件",
    sampleCountText: "野生型: 1 个菌株",
    fileCountText: "文件: 8 个",
    datasetName: "01_课题立项文献及野生型序列库",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 2,
    piNote: "立项合理，准予进入知识库构建与计算设计阶段",
    issuePendingCount: 0,
    issueTotalCount: 3,
    issueReplyCount: 3,
    chatNote: "阶段目标论证完毕，技术指标经全体会议确认"
  },
  {
    id: "step-2",
    order: 2,
    title: "基础数据与知识库整理",
    category: "干实验 · 知识库",
    description: "汇总 Aspergillus niger 等 16 种真菌植酸酶多序列比对、同源晶体结构与功能注释",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-04-05 11:20",
    leadPerson: "赵一凡 博士",
    schemeTitle: "植酸酶序列结构及突变热点数据库构建方案",
    schemeCount: 1,
    refCount: 28,
    schemeNote: "建立包含 420 篇文献的突变效应矩阵与结构拓扑标注库",
    reportSummary: "产出野生型 AppA 高分辨率 1.9Å 晶体结构优化模型及柔性区动力学基准数据",
    reportCount: 2,
    indicatorCount: 3,
    attachmentName: "《AppA_Homology_KnowledgeBase_Summary.xlsx》",
    datasetSummary: "1 个结构集 · 3 个比对矩阵",
    sampleCountText: "结构: 16 个PDB",
    fileCountText: "文件: 12 个",
    datasetName: "02_植酸酶晶体拓扑与多序列比对集",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 1,
    piNote: "知识库数据详实，结构骨架定义明确",
    issuePendingCount: 0,
    issueTotalCount: 1,
    issueReplyCount: 1,
    chatNote: "结构比对完成，柔性 Loop 区编号已统一标注"
  },
  {
    id: "step-3",
    order: 3,
    title: "计算分析与位点预测",
    category: "干实验 · 结构预测",
    description: "利用 FoldX、Rosetta 及分子动力学 (MD) 模拟识别热敏感区域与能量热点位点",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-05-18 17:45",
    leadPerson: "赵一凡 博士",
    schemeTitle: "自由能计算与耐热性突变位点预测算法方案",
    schemeCount: 2,
    refCount: 8,
    schemeNote: "聚焦 B-factor 异常偏高区与盐桥网络稀疏界面的残基突变",
    reportSummary: "锁定 14 个高潜力热稳定残基位点（含 3 处可能构建二硫键的双突变位点）",
    reportCount: 2,
    indicatorCount: 5,
    attachmentName: "《FoldX_Rosetta_Energy_Screening_Top14.pdf》",
    datasetSummary: "4 个轨迹集 · 1 个候选位点表",
    sampleCountText: "预测位点: 14 个",
    fileCountText: "文件: 18 个",
    datasetName: "03_MD模拟轨迹及自由能计算预测结果",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 3,
    piNote: "二硫键预测候选具备良好合理性，同意推进文库构建",
    issuePendingCount: 0,
    issueTotalCount: 2,
    issueReplyCount: 2,
    chatNote: "已剔除 2 个严重破坏底物结合口袋通道的突变建议"
  },
  {
    id: "step-4",
    order: 4,
    title: "突变/文库设计",
    category: "分子设计 · 文库规划",
    description: "设计饱和突变引物及组合智能文库，文库容量控制在 1.5×10^4",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-06-02 09:30",
    leadPerson: "赵一凡 博士",
    schemeTitle: "简并引物简易组合突变与文库覆盖度设计方案",
    schemeCount: 1,
    refCount: 4,
    schemeNote: "采用 NNK 简并密码子降低终止密码子频率，确保 95% 以上覆盖率",
    reportSummary: "完成 24 条寡核苷酸合成引物清单与文库多样性模拟评估",
    reportCount: 1,
    indicatorCount: 2,
    attachmentName: "《Library_Degenerate_Primers_List.xlsx》",
    datasetSummary: "1 个引物设计集 · 1 个质量评估表",
    sampleCountText: "引物: 24 条",
    fileCountText: "文件: 3 个",
    datasetName: "04_突变文库引物设计与模拟文件",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 1,
    piNote: "引物退火温度及 GC 含量已复核，符合合成要求",
    issuePendingCount: 0,
    issueTotalCount: 0,
    issueReplyCount: 0,
    chatNote: "已下发基因合成代工厂安排高精度合成"
  },
  {
    id: "step-5",
    order: 5,
    title: "基因合成与载体构建",
    category: "湿实验 · 分子克隆",
    description: "高保真 PCR 扩增突变片段，Golden Gate 组装至毕赤酵母 pPIC9K 表达载体",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-06-25 15:10",
    leadPerson: "王雪 博士后",
    schemeTitle: "pPIC9K-AppA 质粒重组与毕赤酵母电转化质控规范",
    schemeCount: 2,
    refCount: 2,
    schemeNote: "针对毕赤酵母密码子偏好性完成全长基因优化与分泌信号肽融合",
    reportSummary: "克隆测序验证正确率 98.2%，文库转化子数量达到 2.4×10^4",
    reportCount: 2,
    indicatorCount: 3,
    attachmentName: "《Cloning_Sequencing_Validation_Report.pdf》",
    datasetSummary: "1 个测序结果包 · 1 个克隆图谱",
    sampleCountText: "文库克隆: 48 验证克隆",
    fileCountText: "文件: 16 个",
    datasetName: "05_Sanger测序峰图与克隆验证记录",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 2,
    piNote: "电转效率达标，文库丰度充足",
    issuePendingCount: 0,
    issueTotalCount: 1,
    issueReplyCount: 1,
    chatNote: "转化甘油菌已妥善保藏于 -80℃ 超低温冰箱"
  },
  {
    id: "step-6",
    order: 6,
    title: "表达与培养/发酵",
    category: "湿实验 · 诱导发酵",
    description: "96 深孔板高通量甲醇诱导表达，并完成摇瓶 500mL 预放大诱导实验",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-07-15 16:30",
    leadPerson: "陈建国 工程师",
    schemeTitle: "毕赤酵母 96 深孔板甲醇阶段流加诱导发酵工艺",
    schemeCount: 2,
    refCount: 3,
    schemeNote: "控制诱导温度 28℃，每 24h 补充 0.8% 甲醇，总诱导周期 72h",
    reportSummary: "上清液总蛋白表达量达到 2.8 g/L，分泌效率良好且宿主背景杂蛋白较少",
    reportCount: 2,
    indicatorCount: 3,
    attachmentName: "《DeepWell_Fermentation_Batch202607.xlsx》",
    datasetSummary: "2 个发酵参数集 · 1 个OD监控表",
    sampleCountText: "深孔板: 12 块",
    fileCountText: "文件: 6 个",
    datasetName: "06_甲醇流加曲线与发酵监控数据",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 1,
    piNote: "上清表达水平符合微孔板活性初筛标准",
    issuePendingCount: 0,
    issueTotalCount: 1,
    issueReplyCount: 1,
    chatNote: "微孔板分装完成，即刻送入高通量热处理筛选平台"
  },
  {
    id: "step-7",
    order: 7,
    title: "高通量筛选与候选确认",
    category: "湿实验 · 热浴筛选",
    description: "75℃ 水浴热处理 20min 后快速降温，采用钼蓝法测定残余植酸酶活力",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-08-01 18:20",
    leadPerson: "王雪 博士后",
    schemeTitle: "基于钼蓝定磷法的高通量耐温初筛与复筛双重流程",
    schemeCount: 2,
    refCount: 1,
    schemeNote: "设置野生型 WT 及无菌培养基双阴性对照，Z'-factor 达到 0.72",
    reportSummary: "筛选 1,152 个突变克隆，获得 6 个 75℃ 残余酶活提升超 30% 的优势突变体",
    reportCount: 2,
    indicatorCount: 4,
    attachmentName: "《HighThroughput_Screening_Top6_Hit.xlsx》",
    datasetSummary: "3 个酶标仪原始读数 · 1 个复筛汇总",
    sampleCountText: "筛选孔: 1152 孔",
    fileCountText: "文件: 9 个",
    datasetName: "07_酶标仪吸光度原始矩阵与计算报表",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 2,
    piNote: "命中突变体 Mut-T04 与 Mut-T09 表现优异，同意进行中规模纯化",
    issuePendingCount: 0,
    issueTotalCount: 0,
    issueReplyCount: 0,
    chatNote: "复筛结果重现性良好，CV 值小于 4.5%"
  },
  {
    id: "step-8",
    order: 8,
    title: "蛋白纯化与质量检测",
    category: "湿实验 · 色谱纯化",
    description: "Ni-NTA 亲和层析结合 Superdex 200 凝胶过滤，SDS-PAGE 与 SEC-HPLC 纯度质控",
    status: "completed",
    progressText: "已完成 · 100%",
    progressPercent: 100,
    riskLevel: "low",
    updatedAt: "2026-08-14 11:30",
    leadPerson: "王雪 博士后",
    schemeTitle: "His-tag 植酸酶亲和纯化及去内毒素质控标准操作程序",
    schemeCount: 1,
    refCount: 2,
    schemeNote: "咪唑梯度洗脱（20mM ~ 300mM），脱盐置换为醋酸钠缓冲液 (pH 5.5)",
    reportSummary: "纯化产物纯度 > 95%（SEC 证实为均匀单聚体），得率 85 mg/L",
    reportCount: 1,
    indicatorCount: 3,
    attachmentName: "《Protein_Purification_QC_SDS_PAGE.pdf》",
    datasetSummary: "2 个色谱图谱 · 1 个凝胶成像文件",
    sampleCountText: "纯化批次: 3 批",
    fileCountText: "文件: 7 个",
    datasetName: "08_ÄKTA色谱洗脱峰图与SDS-PAGE电泳图",
    piStatus: "审核通过",
    piReviewer: "张立华",
    piRecordsCount: 1,
    piNote: "样品纯度完全达到酶动力学常数精确表征要求",
    issuePendingCount: 0,
    issueTotalCount: 0,
    issueReplyCount: 0,
    chatNote: "纯化蛋白已按 50μL 分装于 -80℃ 冻存"
  },
  {
    id: "step-9",
    order: 9,
    title: "酶学性质与稳定性表征",
    category: "湿实验 · 性能表征",
    description: "检测酶活、Km、Vmax、kcat/Km、Tm、T50、最适温度、最适pH、底物谱与原始仪器数据",
    status: "in_progress",
    progressText: "延期 · 65%",
    progressPercent: 65,
    riskLevel: "high",
    updatedAt: "2026-08-22 16:30",
    leadPerson: "王雪 博士后",
    schemeTitle: "酶学性质与稳定性表征 实验方案",
    schemeCount: 2,
    refCount: 0,
    schemeNote: "以实验结果、质控状态和下一轮优化建议为主",
    reportSummary: "突变体Mut-T04在65℃下比活力达18,500 U/mg(WT为16,200 U/mg)，但常温(37℃)下kcat下降14.5%。",
    reportCount: 2,
    indicatorCount: 2,
    attachmentName: "《Enzyme_Kinetics_Michaelis_Menten.xlsx》",
    datasetSummary: "1 个数据集 · 1 个原始附件",
    sampleCountText: "样本: 2 个突变体",
    fileCountText: "文件: 5 个",
    datasetName: "09_酶学性质与稳定性表征 原始数据集",
    piStatus: "要求补充修改",
    piReviewer: "张立华",
    piRecordsCount: 0,
    piNote: "点击提交或查看 PI 审核批复意见",
    issuePendingCount: 0,
    issueTotalCount: 0,
    issueReplyCount: 0,
    chatNote: "点击进入阶段协作交流，发起提问或查看答复"
  },
  {
    id: "step-10",
    order: 10,
    title: "迭代优化与下一轮目标设计",
    category: "算法/干实验 · 迭代决策",
    description: "根据动力学权衡数据，设计活性位点柔性 Loop 补偿突变，启动 R2 轮次",
    status: "pending",
    progressText: "未启动 · 0%",
    progressPercent: 0,
    riskLevel: "low",
    updatedAt: "待更新",
    leadPerson: "赵一凡 博士",
    schemeTitle: "R2 轮次刚柔平衡突变体设计指南",
    schemeCount: 0,
    refCount: 0,
    schemeNote: "待阶段 09 PI 终审验收后正式下发执行",
    reportSummary: "尚未产生交付报表",
    reportCount: 0,
    indicatorCount: 0,
    attachmentName: "暂无附件",
    datasetSummary: "0 个数据集",
    sampleCountText: "样本: 0",
    fileCountText: "文件: 0",
    datasetName: "10_迭代优化设计文档集",
    piStatus: "待提交",
    piReviewer: "张立华",
    piRecordsCount: 0,
    piNote: "前置阶段未结项",
    issuePendingCount: 0,
    issueTotalCount: 0,
    issueReplyCount: 0,
    chatNote: "暂无讨论记录"
  },
  {
    id: "step-11",
    order: 11,
    title: "成果归档",
    category: "成果管理 · 结题归档",
    description: "实验原始记录规范化归档、专利交底书撰写及工试交付包准备",
    status: "pending",
    progressText: "未启动 · 0%",
    progressPercent: 0,
    riskLevel: "low",
    updatedAt: "待更新",
    leadPerson: "刘敏 知识产权专员",
    schemeTitle: "知识产权申报与成果交付物封存管理规范",
    schemeCount: 0,
    refCount: 0,
    schemeNote: "涵盖序列发明专利与发酵工艺专有技术交底",
    reportSummary: "尚未产生归档报告",
    reportCount: 0,
    indicatorCount: 0,
    attachmentName: "暂无附件",
    datasetSummary: "0 个数据集",
    sampleCountText: "样本: 0",
    fileCountText: "文件: 0",
    datasetName: "11_最终归档数据包与专利材料",
    piStatus: "待提交",
    piReviewer: "张立华",
    piRecordsCount: 0,
    piNote: "待全流程结束后统一签署",
    issuePendingCount: 0,
    issueTotalCount: 0,
    issueReplyCount: 0,
    chatNote: "暂无讨论记录"
  }
];
