import { verifiedQuality } from '../lib/reviewDomain';
import { useAccessibleDatasets } from '../lib/researchAccess';
import { useEffect, useState } from 'react';
import { Database, Upload, ListTree } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAccessibleProjects } from '../lib/researchAccess';
import { useSamples } from '../lib/sampleStore';
import { datasetsAtNode, datasetLocation, DATASET_CATEGORIES, type ResearchDataset } from '../lib/datasetStore';
import { DatasetEditor } from './DatasetEditor';
import { DatasetDetail, DatasetDelete } from './DatasetViews';
import { sampleControl } from './SampleEditor';

export function DatasetManagement({ initialDetailId = "", onDetailConsumed }: { initialDetailId?: string; onDetailConsumed?: () => void } = {}) {
  const [projects]=useAccessibleProjects(),samples=useSamples(),datasets=useAccessibleDatasets();
  const [quality,setQuality]=useState('all');
  const [category,setCategory]=useState('all'),[projectId,setProjectId]=useState('all'),[nodeId,setNodeId]=useState('all'),[sampleId,setSampleId]=useState('all'),[query,setQuery]=useState(''),[view,setView]=useState('list'),[page,setPage]=useState(1);
  const [editor,setEditor]=useState<ResearchDataset|null|undefined>(),[detail,setDetail]=useState(''),[deleting,setDeleting]=useState<ResearchDataset|null>(null);
  useEffect(() => { if (initialDetailId) { setView("list"); setDetail(initialDetailId); onDetailConsumed?.(); } }, [initialDetailId, onDetailConsumed]);
  const visible=datasets.filter(d=>{
    if(quality!=='all' && (quality==='复核'?verifiedQuality(d)||d.quality==='异常':d.quality!==quality))return false;
    if(category!=='all'&&d.category!==category)return false;
    if(projectId!=='all'&&d.projectId!==projectId)return false;
    if(nodeId==='unassigned'&&projects.find(p=>p.id===d.projectId)?.steps?.some(n=>n.id===d.nodeId))return false;
    if(nodeId!=='all'&&nodeId!=='unassigned'&&d.nodeId!==nodeId)return false;
    if(sampleId!=='all'&&!d.sampleIds.includes(sampleId))return false;
    const loc=datasetLocation(d,projects);return `${d.id} ${d.name} ${loc.project} ${loc.node} ${d.instrument} ${d.files.map(f=>f.name).join(' ')} ${d.sampleIds.map(id=>{const s=samples.find(s=>s.id===id);return `${s?.number||''} ${s?.name||''}`;}).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase());
  });
  const pageCount=Math.max(1,Math.ceil(visible.length/10)),currentPage=Math.min(page,pageCount),unassigned=datasets.filter(d=>!projects.find(p=>p.id===d.projectId)?.steps?.some(s=>s.id===d.nodeId));
  const filter=(fn:()=>void)=>{fn();setPage(1);};
  return <div className="p-6 space-y-4 min-w-0"><div className="flex flex-wrap justify-between gap-3 items-center"><div><h1 className="font-bold text-xl flex items-center gap-2"><Database className="size-5 text-sky-600"/>数据集管理</h1><p className="text-sm text-slate-500 mt-1">项目节点、数据文件与样本统一关联，可双向追溯。</p></div><Button onClick={()=>setEditor(null)}><Upload className="size-4 mr-1"/>上传数据集</Button></div>
    <div className="flex gap-2"><Button variant={view==='list'?'default':'outline'} onClick={()=>setView('list')}>数据集台账</Button><Button variant={view==='relations'?'default':'outline'} onClick={()=>setView('relations')}><ListTree className="size-4 mr-1"/>节点对应关系</Button></div>
    {view==='list'?<><div className="flex flex-wrap gap-2 p-3 border bg-white rounded-xl">{[['all','全部数据集'],...Object.entries(DATASET_CATEGORIES)].map(([id,name])=><Button key={id} size="sm" variant={category===id?'default':'ghost'} onClick={()=>filter(()=>setCategory(id))}>{name} {id==='all'?datasets.length:datasets.filter(d=>d.category===id).length}</Button>)}</div>
      <div className="flex flex-wrap gap-2"><input aria-label="搜索数据集" className={sampleControl+' sm:w-72'} placeholder="搜索数据集、文件、样本或节点" value={query} onChange={e=>filter(()=>setQuery(e.target.value))}/>
        <select aria-label="数据集项目筛选" className={sampleControl+' sm:w-60'} value={projectId} onChange={e=>filter(()=>{setProjectId(e.target.value);setNodeId('all');})}><option value="all">全部关联项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
        <select aria-label="数据集节点筛选" className={sampleControl+' sm:w-56'} value={nodeId} onChange={e=>filter(()=>setNodeId(e.target.value))}><option value="all">全部实验节点</option><option value="unassigned">待关联节点</option>{projects.filter(p=>projectId==='all'||p.id===projectId).map(p=><optgroup key={p.id} label={p.number}>{p.steps?.map(n=><option key={n.id} value={n.id}>{n.order}. {n.title}</option>)}</optgroup>)}</select>
        <select aria-label="数据集样本筛选" className={sampleControl+' sm:w-52'} value={sampleId} onChange={e=>filter(()=>setSampleId(e.target.value))}><option value="all">全部来源样本</option>{samples.map(s=><option key={s.id} value={s.id}>{s.number} · {s.name}</option>)}</select>
<select aria-label="数据集质检筛选" className={sampleControl+' sm:w-44'} value={quality} onChange={e=>filter(()=>setQuality(e.target.value))}><option value="all">全部质检状态</option><option value="复核">待质检 / 复核</option><option>合格</option><option>异常</option></select>
      </div><div className="border rounded-xl overflow-x-auto bg-white"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['数据集名称 / 编号','关联项目','实验节点','文件','关联样本','质检结果','操作'].map(h=><th key={h} className="p-3 text-left whitespace-nowrap">{h}</th>)}</tr></thead><tbody className="divide-y">{visible.slice((currentPage-1)*10,currentPage*10).map(d=>{const loc=datasetLocation(d,projects);return <tr key={d.id} data-dataset-id={d.id}><td className="p-3 min-w-56"><button className="font-semibold text-sky-700 text-left" onClick={()=>setDetail(d.id)}>{d.name}</button><p className="text-[10px] text-slate-400 mt-1 break-all">{d.id}</p><p className="text-[10px] text-slate-400 mt-1">{DATASET_CATEGORIES[d.category]} · {d.owner||'负责人待补充'}</p></td><td className="p-3 min-w-40">{loc.project}</td><td className="p-3 min-w-36">{loc.node}</td><td className="p-3 whitespace-nowrap"><button className="text-sky-700" onClick={()=>setDetail(d.id)}>{d.files.length} 个文件</button><p className="text-[10px] text-slate-400">{d.size}</p></td><td className="p-3 min-w-40">{d.sampleIds.length?<><p className="font-medium">{d.sampleIds.length} 个样本</p>{d.sampleIds.map(id=>{const s=samples.find(s=>s.id===id);return <p key={id} className="text-[10px] mt-1 text-slate-500">{s?.number||id} · {s?.name||'待核对'}</p>;})}</>:<span className="text-slate-400">未关联样本</span>}</td><td className="p-3 whitespace-nowrap"><span className="rounded bg-slate-100 px-2 py-1">{d.quality}</span>{!d.qualityHistory?.length&&d.quality!=='待质检'&&<p className="text-[10px] text-slate-400 mt-1">历史登记，待复核</p>}</td><td className="p-3 whitespace-nowrap"><Button variant="ghost" size="sm" onClick={()=>setDetail(d.id)}>详情 / 质检</Button><Button variant="ghost" size="sm" onClick={()=>setEditor(d)}>编辑关联</Button><Button variant="ghost" size="sm" onClick={()=>setDeleting(d)}>删除</Button></td></tr>;})}{!visible.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-400">暂无匹配数据集</td></tr>}</tbody></table><div className="border-t p-3 flex justify-between items-center text-xs text-slate-500"><span>共 {visible.length} 个数据集 · 第 {currentPage} / {pageCount} 页</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}>上一页</Button><Button variant="outline" size="sm" disabled={currentPage>=pageCount} onClick={()=>setPage(currentPage+1)}>下一页</Button></div></div></div>
    </>:<section className="space-y-3"><p className="text-xs text-slate-500">按项目列出各实验节点的数据集、文件与样本数量，点击数据集查看具体关系。</p>{unassigned.length>0&&<button className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800 w-full text-left" onClick={()=>{setView('list');setProjectId('all');setCategory('all');setSampleId('all');setQuery('');setNodeId('unassigned');setPage(1);}}>有 {unassigned.length} 个历史数据集待明确实验节点，点击补充关联。</button>}
      {projects.map((p,i)=><details key={p.id} open={i===0} className="bg-white border rounded-xl overflow-hidden"><summary className="p-4 font-semibold text-sm cursor-pointer">{p.number} · {p.name}<span className="text-xs text-slate-400 ml-2">{p.steps?.length||0} 个节点</span></summary><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['实验节点','对应数据集','文件数','来源样本数'].map(h=><th key={h} className="text-left p-3">{h}</th>)}</tr></thead><tbody className="divide-y">{p.steps?.map(n=>{const related=datasetsAtNode(datasets,p.id,n.id);return <tr key={n.id}><td className="p-3">{n.order}. {n.title}</td><td className="p-3">{related.length?related.map(d=><button key={d.id} onClick={()=>setDetail(d.id)} className="block text-left text-sky-700 py-1">{d.name}</button>):<span className="text-slate-400">暂无数据集</span>}</td><td className="p-3">{related.reduce((s,d)=>s+d.files.length,0)}</td><td className="p-3">{new Set(related.flatMap(d=>d.sampleIds)).size}</td></tr>;})}</tbody></table></div></details>)}
    </section>}
    {editor!==undefined&&<DatasetEditor dataset={editor||undefined} projectId={projectId==='all'?'':projectId} nodeId={nodeId==='all'||nodeId==='unassigned'?'':nodeId} onClose={()=>setEditor(undefined)}/>}{detail&&<DatasetDetail id={detail} onClose={()=>setDetail('')}/>}{deleting&&<DatasetDelete dataset={deleting} onClose={()=>setDeleting(null)}/>}
  </div>;
}
